# Generated by Django 4.2.7 on 2023-11-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="iPXE_Menu_item",
            fields=[
                (
                    "item_name",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("item_contents", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="iPXE_Menu",
            fields=[
                (
                    "title",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("steps", models.ManyToManyField(to="menu.ipxe_menu_item")),
            ],
        ),
    ]
