# Generated by Django 4.2.7 on 2023-11-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipxe_menu_item",
            name="item_name",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
