# Generated by Django 4.2.7 on 2023-11-14 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_alter_ipxe_menu_item_item_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wimager_Menus",
            fields=[
                (
                    "ipxe_menu_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="menu.ipxe_menu",
                    ),
                ),
            ],
            bases=("menu.ipxe_menu",),
        ),
        migrations.AlterField(
            model_name="ipxe_menu",
            name="steps",
            field=models.ManyToManyField(null=True, to="menu.ipxe_menu_item"),
        ),
    ]
